### ISSUE TITLE
Transient test failure: LoRaWan.Tests.E2E.OTAAJoinTest.Test_OTAA_Join_Send_And_Rejoin_With_Custom_RX2_DR_Single 

### ISSUE THREAD

**Issue by roel4ez** [Azure/iotedge-lorawan-starterkit#1294] opened 2022-01-18 08:24 UTC
Failed E2E run: https://github.com/Azure/iotedge-lorawan-starterkit/runs/4847341871?check_suite_focus=true#step:8:526

**Comment by roel4ez** [comment] 2022-01-19 13:32
maybe related to #1262

**Comment by bastbu** [comment] 2022-03-04 13:16
Since we merged #1397, this is likely solved by that PR. Closing the issue, if we can reproduce it again, let's create a new bug for it.

**Closed by bastbu** 2022-03-04 13:16 UTC
Labels: bug
