### ISSUE TITLE
Rssi Should be in double in PreferredGatewayTableItem.cs

### ISSUE THREAD

**Issue by Mandur** [Azure/iotedge-lorawan-starterkit#1126] opened 2021-12-20 10:01 UTC
RSSI is coming as double from basicstation, we use currently float and int in the tests. Was removed from #1122 following reviewers feedback

**Comment by roel4ez** [comment] 2022-01-05 12:48
duplicate of #1129

**Closed by roel4ez** 2022-01-05 12:48 UTC
Labels: bug
