### ISSUE TITLE
Integration test When_Device_Checks_For_C2D_Message_Uses_Available_Time fails sporadically on CI

### ISSUE THREAD

**Issue by spygi** [Azure/iotedge-lorawan-starterkit#755] opened 2021-11-09 15:52 UTC
## Context

[CI run](https://github.com/Azure/iotedge-lorawan-starterkit/runs/4153257225?check_suite_focus=true)

### Stacktrace
```
  Failed LoRaWan.Tests.Integration.CloudToDeviceMessageTests.When_Device_Checks_For_C2D_Message_Uses_Available_Time(preferredWindow: 2, sendEventDurationInMs: 100, checkMinDuration: 1300, checkMaxDuration: 1510, expectedRX: 2) [1 ms]
  Error Message:
   System.Net.NetworkInformation.NetworkInformationException : An error was encountered while querying information from the operating system.
---- System.AggregateException : One or more errors occurred. (Could not find a part of the path '/sys/class/net/vethd2eb16b/mtu'.)
-------- System.IO.DirectoryNotFoundException : Could not find a part of the path '/sys/class/net/vethd2eb16b/mtu'.
  Stack Trace:
     at System.Net.NetworkInformation.LinuxNetworkInterface.GetLinuxNetworkInterfaces()
   at LoRaWan.Tests.Common.Utility.GetMacAddress() in /home/runner/work/iotedge-lorawan-starterkit/iotedge-lorawan-starterkit/Tests/Common/Utility.cs:line 20
   at LoRaWan.Tests.Common.MessageProcessorTestBase..ctor() in /home/runner/work/iotedge-lorawan-starterkit/iotedge-lorawan-starterkit/Tests/Common/MessageProcessorTestBase.cs:line 51
   at LoRaWan.Tests.Integration.CloudToDeviceMessageTests..ctor()
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
----- Inner Stack Trace -----

----- Inner Stack Trace -----
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at System.Net.NetworkInformation.StringParsingHelpers.ParseRawIntFile(String filePath)
   at System.Net.NetworkInformation.LinuxIPv4InterfaceProperties.GetMtu()
   at System.Net.NetworkInformation.LinuxIPv4InterfaceProperties..ctor(LinuxNetworkInterface linuxNetworkInterface)
   at System.Net.NetworkInformation.LinuxIPInterfaceProperties..ctor(LinuxNetworkInterface lni)
   at System.Net.NetworkInformation.LinuxNetworkInterface..ctor(String name, Int32 index)
   at System.Net.NetworkInformation.LinuxNetworkInterface.GetOrCreate(Dictionary`2 interfaces, String name, Int32 index)
   at System.Net.NetworkInformation.LinuxNetworkInterface.<>c__DisplayClass5_0.<GetLinuxNetworkInterfaces>b__2(String name, LinkLayerAddressInfo* llAddr)
```

**Comment by bastbu** [comment] 2021-11-15 07:52
Possible duplicate of #745. I will update the description there to display the stack trace as part of the bug (discoverability), let's track it in one place

**Closed** 2021-11-15 07:54 UTC
Labels: bug
